### PR TITLE
Thewanderingeditor update map nft images

### PR DESCRIPTION
**Pull request by thewanderingeditor**
Update map NFT images and add silver, gold and diamond

### CODE REVIEW

**Comment by tolbrino** [comment]
@jjperezaguinaga @thewanderingeditor Is this still in progress?

**Comment by thewanderingeditor** [comment]
I just need this to be approved so I can mint the map NFTs and the metadata is already in place.

**Review by QYuQianchen — APPROVED** [review]

**Comment by jjperezaguinaga** [comment]
Probably good to update this one, only the [bronze map](https://dune.xyz/queries/227032) has been minted (and is currently [available](https://github.com/hoprnet/hopr-devrel/tree/release/stake-v1/stake/packages/frontend/public/Map)), but we are adding all here, which means all assets are now (or had been for a month) [public](https://gateway.pinata.cloud/ipfs/QmbWfx1c7LvnxevUYUmVspY1CWR5LoVMzsusTEw8xW1xS5).

@nionis Keep this PR in mind for the deployment of the new site.

**Comment by jjperezaguinaga** [comment]
Just another nudge on this PR to see whether this should be merged cc @tolbrino

**Comment by nionis** [comment]
This has already been approved but @thewanderingeditor has no write access, pressing the button for him.

**Pull request merged**
