### PR TITLE
fix unlock button

### PR DESCRIPTION
**Pull request by nionis**
Re #138

### CODE REVIEW

**Review by jjperezaguinaga — COMMENTED** [review]
Any reason for removing the `yarn.lock`?

**Comment by nionis** [comment]
@jjperezaguinaga that's accidental and am not able to recreate it, debugging

**Comment by jjperezaguinaga** [comment]
> @jjperezaguinaga that's accidental and am not able to recreate it, debugging

Np, approving PR, just wanted to point that out in case it wasn't a mistake.

**Review by jjperezaguinaga — APPROVED** [review]
LGTM. Btw, for some reason the PR preview builds are no longer showing.

**Comment by nionis** [comment]
the lock file must have been created prior to workspaces

**Pull request merged**
