### PR TITLE
Create Surveyor NFT metadata for staking UI and migrate to provider proxy

### PR DESCRIPTION
**Pull request by thewanderingeditor**
Added metadata for Surveyor bronze, silver, gold, diamond NFTs

Changes default provider to provider proxy

### CODE REVIEW

**Review by robertkiel — COMMENTED** [review]
Lgtm.

Haven't checked:
- whether provider proxy URL has any typos
- whether boost values are correct

**Comment by tolbrino** [comment]
I'd rather have @nionis review this since he is working on the staking site now. Also cc @jjperezaguinaga

**Comment by jjperezaguinaga** [comment]
This is fine, but should be created against the `release/stake` UI, let me update and if it looks good we can go ahead and merge.

**Comment by jjperezaguinaga** [comment]
Looks good against `release/stake-v1`, will merge which should trigger a deployment to `stake.hoprnet.org`

**Pull request merged**
